# CI/CD Pipeline Template
# This template provides a comprehensive CI/CD pipeline structure

name: "BMAD CI/CD Pipeline"
version: "1.0.0"
description: "Comprehensive CI/CD pipeline for BMAD project"

# Pipeline Configuration
pipeline:
  stages:
    - name: "code-quality"
      description: "Code quality checks"
      steps:
        - name: "lint"
          command: "npm run lint"
          timeout: "5m"
        - name: "format-check"
          command: "npm run format:check"
          timeout: "3m"
        - name: "security-scan"
          command: "npm audit"
          timeout: "5m"
      
    - name: "unit-tests"
      description: "Unit testing"
      steps:
        - name: "test"
          command: "npm run test:unit"
          timeout: "10m"
        - name: "coverage"
          command: "npm run test:coverage"
          timeout: "5m"
      
    - name: "integration-tests"
      description: "Integration testing"
      steps:
        - name: "integration-test"
          command: "npm run test:integration"
          timeout: "15m"
        - name: "e2e-test"
          command: "npm run test:e2e"
          timeout: "20m"
      
    - name: "build"
      description: "Build application"
      steps:
        - name: "build"
          command: "npm run build"
          timeout: "10m"
        - name: "docker-build"
          command: "docker build -t bmad-app ."
          timeout: "15m"
      
    - name: "security"
      description: "Security scanning"
      steps:
        - name: "vulnerability-scan"
          command: "trivy image bmad-app"
          timeout: "10m"
        - name: "dependency-scan"
          command: "npm audit --audit-level=moderate"
          timeout: "5m"
      
    - name: "deploy-staging"
      description: "Deploy to staging"
      steps:
        - name: "deploy"
          command: "kubectl apply -f k8s/staging/"
          timeout: "10m"
        - name: "health-check"
          command: "kubectl rollout status deployment/bmad-app-staging"
          timeout: "5m"
        - name: "smoke-test"
          command: "npm run test:smoke"
          timeout: "10m"
      
    - name: "deploy-production"
      description: "Deploy to production"
      steps:
        - name: "deploy"
          command: "kubectl apply -f k8s/production/"
          timeout: "15m"
        - name: "health-check"
          command: "kubectl rollout status deployment/bmad-app-production"
          timeout: "10m"
        - name: "post-deployment-test"
          command: "npm run test:post-deployment"
          timeout: "15m"

# Environment Configuration
environments:
  development:
    name: "Development"
    description: "Development environment"
    variables:
      NODE_ENV: "development"
      API_URL: "http://localhost:3000"
      DATABASE_URL: "postgresql://dev:dev@localhost:5432/bmad_dev"
    
  staging:
    name: "Staging"
    description: "Staging environment for testing"
    variables:
      NODE_ENV: "staging"
      API_URL: "https://staging-api.bmad.com"
      DATABASE_URL: "postgresql://staging:staging@staging-db:5432/bmad_staging"
    
  production:
    name: "Production"
    description: "Production environment"
    variables:
      NODE_ENV: "production"
      API_URL: "https://api.bmad.com"
      DATABASE_URL: "postgresql://prod:prod@prod-db:5432/bmad_production"

# Resource Requirements
resources:
  cpu:
    requests: "500m"
    limits: "1000m"
  memory:
    requests: "512Mi"
    limits: "1Gi"
  storage:
    requests: "10Gi"
    limits: "20Gi"

# Security Configuration
security:
  image_scanning: true
  dependency_scanning: true
  secret_scanning: true
  compliance_scanning: true
  
  policies:
    - name: "no-root-user"
      description: "Containers must not run as root"
      enforcement: "required"
    
    - name: "no-privileged-containers"
      description: "Containers must not run in privileged mode"
      enforcement: "required"
    
    - name: "network-policy"
      description: "Network policies must be defined"
      enforcement: "required"

# Monitoring Configuration
monitoring:
  metrics:
    - name: "deployment_success_rate"
      description: "Percentage of successful deployments"
      target: "95%"
    
    - name: "deployment_time"
      description: "Average deployment time"
      target: "< 10 minutes"
    
    - name: "test_coverage"
      description: "Code test coverage"
      target: "> 80%"
    
    - name: "security_vulnerabilities"
      description: "Number of security vulnerabilities"
      target: "0 critical, < 5 total"

# Alerting Configuration
alerts:
  - name: "deployment_failure"
    description: "Deployment failed"
    severity: "critical"
    channels: ["slack", "pagerduty"]
    
  - name: "test_failure"
    description: "Tests failed"
    severity: "high"
    channels: ["slack"]
    
  - name: "security_vulnerability"
    description: "Security vulnerability detected"
    severity: "high"
    channels: ["slack", "pagerduty"]
    
  - name: "performance_degradation"
    description: "Performance degradation detected"
    severity: "medium"
    channels: ["slack"]

# Rollback Configuration
rollback:
  automatic: true
  triggers:
    - health_check_failure: true
    - performance_degradation: true
    - security_vulnerability: true
  
  strategy:
    type: "blue-green"
    health_check_timeout: "5m"
    rollback_timeout: "10m"

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: "30 days"
  locations:
    - type: "s3"
      bucket: "bmad-backups"
      region: "us-west-2"
    - type: "local"
      path: "/backups"

# Documentation
documentation:
  runbooks:
    - name: "deployment-troubleshooting"
      description: "Troubleshooting guide for deployment issues"
      url: "https://docs.bmad.com/runbooks/deployment"
    
    - name: "security-incident-response"
      description: "Security incident response procedures"
      url: "https://docs.bmad.com/runbooks/security"
    
    - name: "performance-optimization"
      description: "Performance optimization guide"
      url: "https://docs.bmad.com/runbooks/performance"

# Compliance
compliance:
  frameworks:
    - name: "SOC 2"
      status: "compliant"
      last_audit: "2024-01-15"
    
    - name: "ISO 27001"
      status: "compliant"
      last_audit: "2024-02-20"
    
    - name: "GDPR"
      status: "compliant"
      last_audit: "2024-03-10"

# Cost Optimization
cost_optimization:
  strategies:
    - name: "spot_instances"
      description: "Use spot instances for non-critical workloads"
      enabled: true
    
    - name: "auto_scaling"
      description: "Automatic scaling based on demand"
      enabled: true
    
    - name: "resource_rightsizing"
      description: "Right-size resources based on usage"
      enabled: true
    
    - name: "reserved_instances"
      description: "Purchase reserved instances for predictable workloads"
      enabled: true 