[tool.ruff]
# Exclude test files from unused import and variable checks
[tool.ruff.per-file-ignores]
"tests/**/*.py" = ["F401", "F841"]
"**/test_*.py" = ["F401", "F841"]
"**/*_test.py" = ["F401", "F841"] 