[tool.ruff]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "DTZ", "T10", "EM", "EXE", "FA", "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SLOT", "SIM", "TID", "TCH", "ARG", "PTH", "ERA", "PD", "PGH", "PL", "TRY", "FLY", "PERF", "FURB", "LOG", "RUF"]
ignore = ["E501", "E203", "E722"]
exclude = ["tests/*", "**/__pycache__", "**/.git", "**/.venv", "**/node_modules", "**/.pytest_cache", "**/htmlcov", "**/.coverage", "**/dist", "**/build", "**/.mypy_cache", "**/.ruff_cache"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["F401", "F841", "E722", "F821"]
"**/test_*.py" = ["F401", "F841", "E722", "F821"]
"**/*_test.py" = ["F401", "F841", "E722", "F821"]
"bmad/resources/templates/**/*.py" = ["F821", "E402", "F401"]
"cli/**/*.py" = ["F541", "E741"]
"integrations/**/*.py" = ["F541", "F841"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto" 